# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# The name we use for this project when interacting with Expeditor Slack App
project:
  alias: azure-chef-extension

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: eng-infra-sustaining

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true

pipelines:
  - publish/pipeline:
      description: Publish azure-chef-extension to Azure cloud
      definition: .expeditor/publish.pipeline.yml
  
subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - trigger_pipeline:publish/pipeline:
          ignore_labels:
            - "Expeditor: Skip Publish to Public"
            - "Expeditor: Skip All"
          only_if_modified:
            - VERSION
