name: Chronoguard

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * 1'  # weekly Monday reminder

jobs:
  chronoguard:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: jaymzh/chronoguard@dc362c4a213230fcc9f3394168eca6f2365aaf5b # main
        with:
          files: ChefExtensionHandler/bin/shared.sh,ChefExtensionHandler/bin/shared.ps1
